### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Razgort** [stefanoslig/angular-ngrx-nx-realworld-example-app#9] opened 2019-06-25 15:45 UTC
Hello guys i just clones and npm installed your app, but i'm getting the following compile error:
WARNING in Circular dependency detected:
libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts

WARNING in Circular dependency detected:
libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts

WARNING in Circular dependency detected:
libs\profile\src\lib\+state\profile.actions.ts -> libs\profile\src\lib\+state\profile.reducer.ts -> libs\profile\src\lib\+state\profile.actions.ts

WARNING in Circular dependency detected:
libs\profile\src\lib\+state\profile.reducer.ts -> libs\profile\src\lib\+state\profile.actions.ts -> libs\profile\src\lib\+state\profile.reducer.ts
ERROR in F:/Workspaces/Source/angular-ngrx-nx-realworld-example-app/libs/editor/src/lib/+state/editor.actions.ts 36:12-23
"export 'ArticleData' was not found in '@angular-ngrx-nx-realworld-example-app/api'
ERROR in F:/Workspaces/Source/angular-ngrx-nx-realworld-example-app/libs/ngrx-forms/src/lib/+state/ngrx-forms.actions.ts 46:12-18
"export 'Errors' was not found in './ngrx-forms.reducer'
ERROR in F:/Workspaces/Source/angular-ngrx-nx-realworld-example-app/libs/profile/src/lib/+state/profile.actions.ts 30:12-19
"export 'Profile' was not found in './profile.reducer'
ERROR in F:/Workspaces/Source/angular-ngrx-nx-realworld-example-app/libs/profile/src/lib/+state/profile.actions.ts 57:12-19
"export 'Profile' was not found in './profile.reducer'
ERROR in F:/Workspaces/Source/angular-ngrx-nx-realworld-example-app/libs/profile/src/lib/+state/profile.actions.ts 84:12-19
"export 'Profile' was not found in './profile.reducer'

Thanks! in advance for help

**Comment by stefanoslig** [comment] 2019-06-25 18:24
Hi, thanks for reporting that. Unfortunately,  I can't reproduce it. Have you changed something?

**Comment by Razgort** [comment] 2019-06-26 04:07
Hi, no sry i changed nothing in your app just clone and install ...

**Comment by Razgort** [comment] 2019-06-26 05:41
Re, i want to precise that i m under windows
And when checking those file in error , you make a circular dependency between actions and reducer is it on purpose ?
I would love to use your structure in a very particular case can we discuss about it by mail or a conf call my email : a.moulay@meta2i.com

**Comment by Razgort** [comment] 2019-06-26 06:15
i managed to correct most error by changing

```
import { ValidatorFn } from '@angular/forms';

import { NgrxFormsAction, NgrxFormsActionTypes } from './ngrx-forms.actions';

export interface NgrxForms {
  data: any;
  structure: Field[];
  valid: boolean;
  errors: Errors;
  touched: boolean;
}

export interface NgrxFormsState {
  readonly ngrxForms: NgrxForms;
}

export interface Field {
  type: FieldType;
  name: string;
  label?: string;
  placeholder?: string;
  validator?: ValidatorFn[];
  attrs?: any;
}

export type FieldType = 'INPUT' | 'TEXTAREA';

interface Errors {
  [key: string]: string;
}
```
```


import { Action } from '@ngrx/store';
 interface Profile {
  username: string;
  bio: string;
  image: string;
  following: boolean;
  loading: boolean;
}
```
in files concerned instead of importing but now i have an error with shared libs import : 


ERROR in F:/Workspaces/Source/angular-ngrx-nx-realworld-example-app/libs/editor/src/lib/+state/editor.actions.ts 36:12-23
"export 'ArticleData' was not found in '@angular-ngrx-nx-realworld-example-app/api'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

**Comment by funnyfrish** [comment] 2019-06-27 08:54
same errors in my case

yarn run v1.16.0
$ ng serve

Date: 2019-06-27T07:54:12.112Z
Hash: 2c6f7d96a1b88ae57854
Time: 13987ms
chunk {angular-ngrx-nx-realworld-example-app-article-src-lib-article-module} angular-ngrx-nx-realworld-example-app-article-src-lib-article-module.js, angular-ngrx-nx-realworld-example-app-article-src-lib-article-module.js.map (angular-ngrx-nx-realworld-example-app-
article-src-lib-article-module) 112 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-editor-src-lib-editor-module} angular-ngrx-nx-realworld-example-app-editor-src-lib-editor-module.js, angular-ngrx-nx-realworld-example-app-editor-src-lib-editor-module.js.map (angular-ngrx-nx-realworld-example-app-editor
-src-lib-editor-module) 30.4 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-home-src-lib-home-module} angular-ngrx-nx-realworld-example-app-home-src-lib-home-module.js, angular-ngrx-nx-realworld-example-app-home-src-lib-home-module.js.map (angular-ngrx-nx-realworld-example-app-home-src-lib-home-
module) 30.6 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-profile-src-lib-profile-module} angular-ngrx-nx-realworld-example-app-profile-src-lib-profile-module.js, angular-ngrx-nx-realworld-example-app-profile-src-lib-profile-module.js.map (angular-ngrx-nx-realworld-example-app-
profile-src-lib-profile-module) 40.3 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-settings-src-lib-settings-module} angular-ngrx-nx-realworld-example-app-settings-src-lib-settings-module.js, angular-ngrx-nx-realworld-example-app-settings-src-lib-settings-module.js.map (angular-ngrx-nx-realworld-exampl
e-app-settings-src-lib-settings-module) 21.2 kB  [rendered]
chunk {default~angular-ngrx-nx-realworld-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e} default~angular-ngrx-nx-realworld-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e.js, default~angular-ngrx-nx-realworld
-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e.js.map (default~angular-ngrx-nx-realworld-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e) 54.3 kB  [rendered]
chunk {main} main.js, main.js.map (main) 151 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 289 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.64 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.52 MB [initial] [rendered]

WARNING in Circular dependency detected:
libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts

WARNING in Circular dependency detected:
libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts

WARNING in Circular dependency detected:
libs\profile\src\lib\+state\profile.actions.ts -> libs\profile\src\lib\+state\profile.reducer.ts -> libs\profile\src\lib\+state\profile.actions.ts

WARNING in Circular dependency detected:
libs\profile\src\lib\+state\profile.reducer.ts -> libs\profile\src\lib\+state\profile.actions.ts -> libs\profile\src\lib\+state\profile.reducer.ts

ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/editor/src/lib/+state/editor.actions.ts 36:12-23
"export 'ArticleData' was not found in '@angular-ngrx-nx-realworld-example-app/api'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/ngrx-forms/src/lib/+state/ngrx-forms.actions.ts 46:12-18
"export 'Errors' was not found in './ngrx-forms.reducer'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/profile/src/lib/+state/profile.actions.ts 30:12-19
"export 'Profile' was not found in './profile.reducer'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/profile/src/lib/+state/profile.actions.ts 57:12-19
"export 'Profile' was not found in './profile.reducer'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/profile/src/lib/+state/profile.actions.ts 84:12-19
"export 'Profile' was not found in './profile.reducer'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
Batchvorgang abbrechen (J/N)? ^Cj

C:\dev\angular-ngrx-nx-realworld-example-app-master>yarn start
yarn run v1.16.0
$ ng serve

Date: 2019-06-27T08:44:29.542Z
Hash: 2c6f7d96a1b88ae57854
Time: 13705ms
chunk {angular-ngrx-nx-realworld-example-app-article-src-lib-article-module} angular-ngrx-nx-realworld-example-app-article-src-lib-article-module.js, angular-ngrx-nx-realworld-example-app-article-src-lib-article-module.js.map (angular-ngrx-nx-realworld-example-app-
article-src-lib-article-module) 112 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-editor-src-lib-editor-module} angular-ngrx-nx-realworld-example-app-editor-src-lib-editor-module.js, angular-ngrx-nx-realworld-example-app-editor-src-lib-editor-module.js.map (angular-ngrx-nx-realworld-example-app-editor
-src-lib-editor-module) 30.4 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-home-src-lib-home-module} angular-ngrx-nx-realworld-example-app-home-src-lib-home-module.js, angular-ngrx-nx-realworld-example-app-home-src-lib-home-module.js.map (angular-ngrx-nx-realworld-example-app-home-src-lib-home-
module) 30.6 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-profile-src-lib-profile-module} angular-ngrx-nx-realworld-example-app-profile-src-lib-profile-module.js, angular-ngrx-nx-realworld-example-app-profile-src-lib-profile-module.js.map (angular-ngrx-nx-realworld-example-app-
profile-src-lib-profile-module) 40.3 kB  [rendered]
chunk {angular-ngrx-nx-realworld-example-app-settings-src-lib-settings-module} angular-ngrx-nx-realworld-example-app-settings-src-lib-settings-module.js, angular-ngrx-nx-realworld-example-app-settings-src-lib-settings-module.js.map (angular-ngrx-nx-realworld-exampl
e-app-settings-src-lib-settings-module) 21.2 kB  [rendered]
chunk {default~angular-ngrx-nx-realworld-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e} default~angular-ngrx-nx-realworld-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e.js, default~angular-ngrx-nx-realworld
-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e.js.map (default~angular-ngrx-nx-realworld-example-app-home-src-lib-home-module~angular-ngrx-nx-realworld-exa~7ed46f7e) 54.3 kB  [rendered]
chunk {main} main.js, main.js.map (main) 151 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 289 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.64 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.52 MB [initial] [rendered]

WARNING in Circular dependency detected:
libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts

WARNING in Circular dependency detected:
libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.actions.ts -> libs\ngrx-forms\src\lib\+state\ngrx-forms.reducer.ts

WARNING in Circular dependency detected:
libs\profile\src\lib\+state\profile.actions.ts -> libs\profile\src\lib\+state\profile.reducer.ts -> libs\profile\src\lib\+state\profile.actions.ts

WARNING in Circular dependency detected:
libs\profile\src\lib\+state\profile.reducer.ts -> libs\profile\src\lib\+state\profile.actions.ts -> libs\profile\src\lib\+state\profile.reducer.ts

ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/editor/src/lib/+state/editor.actions.ts 36:12-23
"export 'ArticleData' was not found in '@angular-ngrx-nx-realworld-example-app/api'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/ngrx-forms/src/lib/+state/ngrx-forms.actions.ts 46:12-18
"export 'Errors' was not found in './ngrx-forms.reducer'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/profile/src/lib/+state/profile.actions.ts 30:12-19
"export 'Profile' was not found in './profile.reducer'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/profile/src/lib/+state/profile.actions.ts 57:12-19
"export 'Profile' was not found in './profile.reducer'
ERROR in C:/dev/angular-ngrx-nx-realworld-example-app-master/libs/profile/src/lib/+state/profile.actions.ts 84:12-19
"export 'Profile' was not found in './profile.reducer'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

**Comment by stefanoslig** [comment] 2019-06-27 09:02
Yeah, I was able to reproduce it in a windows machine. I'll push a fix. Thank you guys!

**Comment by funnyfrish** [comment] 2019-06-27 10:46
Would be great when we can get a quickfix so i can start today with the monorepo

**Comment by stefanoslig** [comment] 2019-06-27 11:57
it will be fixed until tomorrow

**Comment by stefanoslig** [comment] 2019-06-27 20:40
It should be ok now

**Comment by stefanoslig** [comment] 2019-06-27 20:41
Fixed

**Closed** 2019-06-27 20:44 UTC
